//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Intranet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIA.Intranet.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddEditNotDeleteRole.
        /// </summary>
        public static string AddEditNotDeleteRole {
            get {
                return ResourceManager.GetString("AddEditNotDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddNotEditNotDeleteRole.
        /// </summary>
        public static string AddNotEditNotDeleteRole {
            get {
                return ResourceManager.GetString("AddNotEditNotDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADGroup.
        /// </summary>
        public static string ADGroup {
            get {
                return ResourceManager.GetString("ADGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm nâng cao.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [I-Office] Approval.
        /// </summary>
        public static string ApprovalWorkflowName {
            get {
                return ResourceManager.GetString("ApprovalWorkflowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm nhân viên.
        /// </summary>
        public static string AuthenticatedGroup {
            get {
                return ResourceManager.GetString("AuthenticatedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm cơ bản.
        /// </summary>
        public static string BasicSearch {
            get {
                return ResourceManager.GetString("BasicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        public static string CAMLDateFormat {
            get {
                return ResourceManager.GetString("CAMLDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu lực.
        /// </summary>
        public static string ChoiceEffect {
            get {
                return ResourceManager.GetString("ChoiceEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hiệu lực.
        /// </summary>
        public static string ChoiceExpire {
            get {
                return ResourceManager.GetString("ChoiceExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm ban quản lý.
        /// </summary>
        public static string DirectorGroup {
            get {
                return ResourceManager.GetString("DirectorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm ban quản lý.
        /// </summary>
        public static string DirectorGroupDescription {
            get {
                return ResourceManager.GetString("DirectorGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thảo luận.
        /// </summary>
        public static string DiscustionDisplay {
            get {
                return ResourceManager.GetString("DiscustionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị thư viện tài liệu.
        /// </summary>
        public static string DocumentAdminGroup {
            get {
                return ResourceManager.GetString("DocumentAdminGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;div&gt;&lt;h2&gt;Đang tạo thư viện&lt;/h2&gt;&lt;/div&gt;&quot;.
        /// </summary>
        public static string DocumentLeadingHTML {
            get {
                return ResourceManager.GetString("DocumentLeadingHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DocumentTrailingHTML {
            get {
                return ResourceManager.GetString("DocumentTrailingHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditControlBlock.
        /// </summary>
        public static string ECBEditControlBlock {
            get {
                return ResourceManager.GetString("ECBEditControlBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý phát sinh.
        /// </summary>
        public static string ECBProjectDerivedExpenses {
            get {
                return ResourceManager.GetString("ECBProjectDerivedExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thảo luận.
        /// </summary>
        public static string ECBProjectDiscustion {
            get {
                return ResourceManager.GetString("ECBProjectDiscustion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ dự án.
        /// </summary>
        public static string ECBProjectDocument {
            get {
                return ResourceManager.GetString("ECBProjectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý công việc.
        /// </summary>
        public static string ECBProjectManageTask {
            get {
                return ResourceManager.GetString("ECBProjectManageTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditNotAddNotDeleteRole.
        /// </summary>
        public static string EditNotAddNotDeleteRole {
            get {
                return ResourceManager.GetString("EditNotAddNotDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Templates.
        /// </summary>
        public static string EmailTemplatesListName {
            get {
                return ResourceManager.GetString("EmailTemplatesListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ cá nhân.
        /// </summary>
        public static string EmployeeProfileListDescription {
            get {
                return ResourceManager.GetString("EmployeeProfileListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ cá nhân.
        /// </summary>
        public static string EmployeeProfileListName {
            get {
                return ResourceManager.GetString("EmployeeProfileListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình độ chuyên môn.
        /// </summary>
        public static string ExpertiseListName {
            get {
                return ResourceManager.GetString("ExpertiseListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoại ngữ.
        /// </summary>
        public static string ForeignLanguageListName {
            get {
                return ResourceManager.GetString("ForeignLanguageListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị timesheet.
        /// </summary>
        public static string GroupTimesheetAdmin {
            get {
                return ResourceManager.GetString("GroupTimesheetAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân sự.
        /// </summary>
        public static string HRDepartment {
            get {
                return ResourceManager.GetString("HRDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm quản lý phòng ban và nhân viên.
        /// </summary>
        public static string HRGroup {
            get {
                return ResourceManager.GetString("HRGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm quản lý phòng ban và nhân viên.
        /// </summary>
        public static string HRGroupDescription {
            get {
                return ResourceManager.GetString("HRGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu không hợp lệ.
        /// </summary>
        public static string InvalidErrorMessage {
            get {
                return ResourceManager.GetString("InvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban điều hành.
        /// </summary>
        public static string ManagementGroup {
            get {
                return ResourceManager.GetString("ManagementGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string NULL {
            get {
                return ResourceManager.GetString("NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị dữ liệu.
        /// </summary>
        public static string PortalAdminGroup {
            get {
                return ResourceManager.GetString("PortalAdminGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string PositionListName {
            get {
                return ResourceManager.GetString("PositionListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hồ sơ.
        /// </summary>
        public static string ProfileTypeListName {
            get {
                return ResourceManager.GetString("ProfileTypeListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị dự án.
        /// </summary>
        public static string ProjectAdminGroup {
            get {
                return ResourceManager.GetString("ProjectAdminGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tìm kiếm.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm quản trị hệ thống.
        /// </summary>
        public static string SiteAdminGroup {
            get {
                return ResourceManager.GetString("SiteAdminGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm quản trị hệ thống.
        /// </summary>
        public static string SiteAdminGroupDescription {
            get {
                return ResourceManager.GetString("SiteAdminGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffGroup.
        /// </summary>
        public static string StaffGroup {
            get {
                return ResourceManager.GetString("StaffGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string SubAnnouncementListName {
            get {
                return ResourceManager.GetString("SubAnnouncementListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch làm việc.
        /// </summary>
        public static string SubCalendarListName {
            get {
                return ResourceManager.GetString("SubCalendarListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thảo luận.
        /// </summary>
        public static string SubDiscussionListName {
            get {
                return ResourceManager.GetString("SubDiscussionListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu.
        /// </summary>
        public static string SubDocumentListName {
            get {
                return ResourceManager.GetString("SubDocumentListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminGroup.
        /// </summary>
        public static string SubSiteAdminGroup {
            get {
                return ResourceManager.GetString("SubSiteAdminGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên tiêu biểu.
        /// </summary>
        public static string TopEmployeesListName {
            get {
                return ResourceManager.GetString("TopEmployeesListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string VNDateFormat {
            get {
                return ResourceManager.GetString("VNDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm.
        /// </summary>
        public static string VNDateTimeFormat {
            get {
                return ResourceManager.GetString("VNDateTimeFormat", resourceCulture);
            }
        }
    }
}
