//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.WebControls;
using Microsoft.SharePoint.WebControls;
using Microsoft.SharePoint.Utilities;
using Microsoft.SharePoint;
namespace AIA.Intranet.Infrastructure.Controls
{
    public partial class ImageFieldControl
    {
        protected DropDownList ddlWebs;
        protected DropDownList ddlPictureLibrary;
        protected TextBox tbFormatName;
        protected CheckBox cbOverwrite;
        protected FileUpload fuDefaultPicture;
        protected CheckBox cbClearDefaultPicture;
        protected Image imgDefaultPicture;

        protected InputFormSection ifsImageField;
        protected InputFormControl ifcWeb;
        protected InputFormControl ifcPictureLibrary;
        protected RequiredFieldValidator rfvPictureLibrary;
        protected InputFormControl ifcFormatName;
        protected Label lbFormatNameExample;
        protected InputFormControl ifcOverwrite;
        protected InputFormControl ifcDefaultPicture;

        private void LocalizeControls()
        {
            ifsImageField.Title = SPUtility.GetLocalizedString("$Resources:ExtendedProperties", "ImageField", (uint)SPContext.Current.Web.Locale.LCID);
            ifcWeb.LabelText = SPUtility.GetLocalizedString("$Resources:Web", "ImageField", (uint)SPContext.Current.Web.Locale.LCID);
            ifcPictureLibrary.LabelText = SPUtility.GetLocalizedString("$Resources:PictureLibrary", "ImageField", (uint)SPContext.Current.Web.Locale.LCID);
            rfvPictureLibrary.ErrorMessage = SPUtility.GetLocalizedString("$Resources:ErrorPictureLibrary", "ImageField", (uint)SPContext.Current.Web.Locale.LCID);
            ifcFormatName.LabelText = SPUtility.GetLocalizedString("$Resources:FormatName", "ImageField", (uint)SPContext.Current.Web.Locale.LCID);
            lbFormatNameExample.Text = SPUtility.GetLocalizedString("$Resources:FormatNameExample", "ImageField", (uint)SPContext.Current.Web.Locale.LCID);
            ifcOverwrite.LabelText = SPUtility.GetLocalizedString("$Resources:Overwrite", "ImageField", (uint)SPContext.Current.Web.Locale.LCID);
            ifcDefaultPicture.LabelText = SPUtility.GetLocalizedString("$Resources:DefaultPicture", "ImageField", (uint)SPContext.Current.Web.Locale.LCID);
            cbClearDefaultPicture.Text = SPUtility.GetLocalizedString("$Resources:ClearDefaultPicture", "ImageField", (uint)SPContext.Current.Web.Locale.LCID);
        }
    }
}
 