//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Intranet.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApprovalWorkflowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApprovalWorkflowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIA.Intranet.Infrastructure.Resources.ApprovalWorkflowResources", typeof(ApprovalWorkflowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người duyệt.
        /// </summary>
        internal static string ApprovalWF_InitPage_Approvers {
            get {
                return ResourceManager.GetString("ApprovalWF_InitPage_Approvers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung email.
        /// </summary>
        internal static string ApprovalWF_InitPage_EmailBody {
            get {
                return ResourceManager.GetString("ApprovalWF_InitPage_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung thư điện tử gửi qua mail cho người duyệt.
        /// </summary>
        internal static string ApprovalWF_InitPage_EmailMessage {
            get {
                return ResourceManager.GetString("ApprovalWF_InitPage_EmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề email.
        /// </summary>
        internal static string ApprovalWF_InitPage_EmailTitle {
            get {
                return ResourceManager.GetString("ApprovalWF_InitPage_EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông điệp gửi cho người duyệt.
        /// </summary>
        internal static string ApprovalWF_InitPage_MessageToApprover {
            get {
                return ResourceManager.GetString("ApprovalWF_InitPage_MessageToApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn duyệt cho tất cả cấp duyệt.
        /// </summary>
        internal static string ApprovalWF_InitPage_TaskDueDate {
            get {
                return ResourceManager.GetString("ApprovalWF_InitPage_TaskDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian hiệu lực trên mỗi yêu cầu.
        /// </summary>
        internal static string ApprovalWF_InitPage_TaskDuration {
            get {
                return ResourceManager.GetString("ApprovalWF_InitPage_TaskDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Manager.
        /// </summary>
        internal static string RadioListApproverType_Manager {
            get {
                return ResourceManager.GetString("RadioListApproverType_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Metadata.
        /// </summary>
        internal static string RadioListApproverType_Metadata {
            get {
                return ResourceManager.GetString("RadioListApproverType_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Users/Groups.
        /// </summary>
        internal static string RadioListApproverType_SpecifyUserGroup {
            get {
                return ResourceManager.GetString("RadioListApproverType_SpecifyUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tài liệu/dữ liệu.
        /// </summary>
        internal static string TaskForm_EditProperties {
            get {
                return ResourceManager.GetString("TaskForm_EditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông điệp.
        /// </summary>
        internal static string TaskForm_Message {
            get {
                return ResourceManager.GetString("TaskForm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        internal static string TaskForm_TaskInstruction {
            get {
                return ResourceManager.GetString("TaskForm_TaskInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string TaskForm_TaskStatus {
            get {
                return ResourceManager.GetString("TaskForm_TaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thông tin tài liệu/dữ liệu.
        /// </summary>
        internal static string TaskForm_ViewProperties {
            get {
                return ResourceManager.GetString("TaskForm_ViewProperties", resourceCulture);
            }
        }
    }
}
