//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIA.Intranet.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIA.Intranet.Infrastructure.Resources.ProjectResources", typeof(ProjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string BTNCancelText {
            get {
                return ResourceManager.GetString("BTNCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        internal static string BTNSearchText {
            get {
                return ResourceManager.GetString("BTNSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị phụ trách.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phát sinh.
        /// </summary>
        internal static string DerivedExpenses {
            get {
                return ResourceManager.GetString("DerivedExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( Tất cả ).
        /// </summary>
        internal static string DropDownSelect {
            get {
                return ResourceManager.GetString("DropDownSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phát sinh.
        /// </summary>
        internal static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người chịu trách nhiệm.
        /// </summary>
        internal static string IssueManager {
            get {
                return ResourceManager.GetString("IssueManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string IssueProgress {
            get {
                return ResourceManager.GetString("IssueProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới phát sinh.
        /// </summary>
        internal static string IssueProgress1 {
            get {
                return ResourceManager.GetString("IssueProgress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thực hiện.
        /// </summary>
        internal static string IssueProgress2 {
            get {
                return ResourceManager.GetString("IssueProgress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thực hiện.
        /// </summary>
        internal static string IssueProgress3 {
            get {
                return ResourceManager.GetString("IssueProgress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người xử lý.
        /// </summary>
        internal static string IssueUser {
            get {
                return ResourceManager.GetString("IssueUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thảo luận dự án.
        /// </summary>
        internal static string List_ProjectDiscussion {
            get {
                return ResourceManager.GetString("List_ProjectDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giám đốc dự án.
        /// </summary>
        internal static string ProgramManager {
            get {
                return ResourceManager.GetString("ProgramManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc thực tế.
        /// </summary>
        internal static string ProjectActualEnd {
            get {
                return ResourceManager.GetString("ProjectActualEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu thực tế.
        /// </summary>
        internal static string ProjectActualStart {
            get {
                return ResourceManager.GetString("ProjectActualStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư ký dự án.
        /// </summary>
        internal static string ProjectClerk {
            get {
                return ResourceManager.GetString("ProjectClerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí phát sinh.
        /// </summary>
        internal static string ProjectDerivedExpenses {
            get {
                return ResourceManager.GetString("ProjectDerivedExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả dự án.
        /// </summary>
        internal static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc.
        /// </summary>
        internal static string ProjectEnd {
            get {
                return ResourceManager.GetString("ProjectEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí đầu tư.
        /// </summary>
        internal static string ProjectExpenses {
            get {
                return ResourceManager.GetString("ProjectExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trưởng dự án.
        /// </summary>
        internal static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên dự án.
        /// </summary>
        internal static string ProjectMember {
            get {
                return ResourceManager.GetString("ProjectMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string ProjectNote {
            get {
                return ResourceManager.GetString("ProjectNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ ưu tiên.
        /// </summary>
        internal static string ProjectPriority {
            get {
                return ResourceManager.GetString("ProjectPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thấp.
        /// </summary>
        internal static string ProjectPriority1 {
            get {
                return ResourceManager.GetString("ProjectPriority1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung bình.
        /// </summary>
        internal static string ProjectPriority2 {
            get {
                return ResourceManager.GetString("ProjectPriority2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cao.
        /// </summary>
        internal static string ProjectPriority3 {
            get {
                return ResourceManager.GetString("ProjectPriority3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % hoàn thành.
        /// </summary>
        internal static string ProjectProgress {
            get {
                return ResourceManager.GetString("ProjectProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin về dự án.
        /// </summary>
        internal static string ProjectSearchWebPartTitle {
            get {
                return ResourceManager.GetString("ProjectSearchWebPartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu.
        /// </summary>
        internal static string ProjectStart {
            get {
                return ResourceManager.GetString("ProjectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string ProjectStatus {
            get {
                return ResourceManager.GetString("ProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa bắt đầu.
        /// </summary>
        internal static string ProjectStatus1 {
            get {
                return ResourceManager.GetString("ProjectStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tiến hành.
        /// </summary>
        internal static string ProjectStatus2 {
            get {
                return ResourceManager.GetString("ProjectStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hoàn thành.
        /// </summary>
        internal static string ProjectStatus3 {
            get {
                return ResourceManager.GetString("ProjectStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị hoãn lại.
        /// </summary>
        internal static string ProjectStatus4 {
            get {
                return ResourceManager.GetString("ProjectStatus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên dự án.
        /// </summary>
        internal static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        internal static string View_AllProject {
            get {
                return ResourceManager.GetString("View_AllProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        internal static string View_CompletedProject {
            get {
                return ResourceManager.GetString("View_CompletedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị hoãn lại.
        /// </summary>
        internal static string View_DelayProject {
            get {
                return ResourceManager.GetString("View_DelayProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tiến hành.
        /// </summary>
        internal static string View_InprogressProject {
            get {
                return ResourceManager.GetString("View_InprogressProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án của tôi.
        /// </summary>
        internal static string View_MyProject {
            get {
                return ResourceManager.GetString("View_MyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa bắt đầu.
        /// </summary>
        internal static string View_NotStartProject {
            get {
                return ResourceManager.GetString("View_NotStartProject", resourceCulture);
            }
        }
    }
}
